name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - name: Zip the build
        run: Compress-Archive -Path dist/TypeCritters-win32-x64/* -DestinationPath dist/TypeCritters-win32-x64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/TypeCritters-win32-x64.zip
          generate_release_notes: true
